enableGlobalCache: true
nodeLinker: node-modules
npmRegistryServer: 'https://registry.yarnpkg.com'
npmScopes:
  kastelll:
    npmAlwaysAuth: true # not required just stealing this from another project that requires it
    npmRegistryServer: 'https://npm.pkg.github.com'
